version: "3.9"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: .dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL="http://localhost:5173/"
    # networks:
    #   - client-server
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: .dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=store
      - DB_USER=postgres
      - DB_PASSWORD=ypostgres
      - DB_HOST=postgres_db
    volumes:
      - static_data:/usr/server/static
    # networks:
    #   - server-db
    #   - client-server
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ypostgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    # networks:
    #   - server-db

volumes:
  postgres_db_data: {}
  static_data: {}
# networks:
#   client-server:
#   server-db:
